#!/bin/sh

RANDOM=$( openssl rand -base64 32 )

wget -O /etc/init.d/play https://raw.githubusercontent.com/davemaple/playframework-nginx-elastic-beanstalk/master/play?random=$RANDOM
chmod +x /etc/init.d/play

wget -O /etc/nginx/conf.d/beanstalk.conf https://raw.githubusercontent.com/davemaple/playframework-nginx-elastic-beanstalk/master/nginx/beanstalk.conf?random=$RANDOM
wget -O /etc/monit.d/monit.conf https://raw.githubusercontent.com/davemaple/playframework-nginx-elastic-beanstalk/master/elasticbeanstalk/containerfiles/monit.conf?random=$RANDOM

wget -O /opt/elasticbeanstalk/hooks/appdeploy/post/01start.sh https://raw.githubusercontent.com/davemaple/playframework-nginx-elastic-beanstalk/master/elasticbeanstalk/hooks/appdeploy/post/01start.sh?random=$RANDOM
wget -O /opt/elasticbeanstalk/hooks/appdeploy/enact/01stop.sh https://raw.githubusercontent.com/davemaple/playframework-nginx-elastic-beanstalk/master/elasticbeanstalk/hooks/appdeploy/enact/01stop.sh?random=$RANDOM

service monit restart
sleep 5
monit restart nginx
monit restart play